- hosts: localhost
  connection: local
  tasks:
  - name: create ad sp
    azure_ad_serviceprincipal:
      app_id: d5a64010-3334-464f-8720-8ad850437eec
      state: present
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
